// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/discount/usecase.go

// Package mock_discount is a generated GoMock package.
package mock_discount

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/majidbl/discount/internal/models"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// DiscountRequest mocks base method.
func (m *MockUseCase) DiscountRequest(ctx context.Context, req *models.Discount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscountRequest", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DiscountRequest indicates an expected call of DiscountRequest.
func (mr *MockUseCaseMockRecorder) DiscountRequest(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscountRequest", reflect.TypeOf((*MockUseCase)(nil).DiscountRequest), ctx, req)
}
