// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/giftcharge/usecase.go

// Package mock_giftcharge is a generated GoMock package.
package mock_giftcharge

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/majidbl/discount/internal/models"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUseCase) Create(ctx context.Context, giftCharge *models.GiftChargeCreateReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, giftCharge)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUseCaseMockRecorder) Create(ctx, giftCharge interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUseCase)(nil).Create), ctx, giftCharge)
}

// GetByCode mocks base method.
func (m *MockUseCase) GetByCode(ctx context.Context, code string) (*models.GiftCharge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*models.GiftCharge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockUseCaseMockRecorder) GetByCode(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockUseCase)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockUseCase) GetByID(ctx context.Context, id int64) (*models.GiftCharge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.GiftCharge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUseCaseMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUseCase)(nil).GetByID), ctx, id)
}

// GetInValidList mocks base method.
func (m *MockUseCase) GetInValidList(ctx context.Context) ([]*models.GiftCharge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInValidList", ctx)
	ret0, _ := ret[0].([]*models.GiftCharge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInValidList indicates an expected call of GetInValidList.
func (mr *MockUseCaseMockRecorder) GetInValidList(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInValidList", reflect.TypeOf((*MockUseCase)(nil).GetInValidList), ctx)
}

// GetList mocks base method.
func (m *MockUseCase) GetList(ctx context.Context) ([]*models.GiftCharge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx)
	ret0, _ := ret[0].([]*models.GiftCharge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockUseCaseMockRecorder) GetList(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockUseCase)(nil).GetList), ctx)
}

// GetValidList mocks base method.
func (m *MockUseCase) GetValidList(ctx context.Context) ([]*models.GiftCharge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidList", ctx)
	ret0, _ := ret[0].([]*models.GiftCharge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidList indicates an expected call of GetValidList.
func (mr *MockUseCaseMockRecorder) GetValidList(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidList", reflect.TypeOf((*MockUseCase)(nil).GetValidList), ctx)
}
